# Generated by Django 5.2.8 on 2025-11-27 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='recruiter',
            field=models.ForeignKey(limit_choices_to={'role': 'recruiter'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to=settings.AUTH_USER_MODEL),
        ),
    ]
